version: '3'

services:
  bot:
    image: docker.pkg.github.com/jaitl/goenglishbot/go-english-bot:<version>
    depends_on:
      - 'mongodb'
    environment:
      - TOKEN=abt
      - USER_ID=123
      - MONGO_DB_URL=mongodb://mongodb:27017
      - AWS_REGION=eu-west-2
      - AWS_KEY=asd
      - AWS_SECRET=qwewe
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
  mongodb:
    image: mongo:4.2
    volumes:
      - ./data/db:/data/db
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
